---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=0.5in

title: "Resume"
author: Tyler S. Clavelle
jobtitle: "Project Researcher, Sustainable Fisheries Group"
address: "1324 B San Andres St. · Santa Barbara · CA 93101"
fontawesome: yes
email: tyler.clavelle@gmail.com
github: tclavelle
phone: "802 578-8701"
web: tylerclavelle.com
updated: no

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# OBJECTIVE

Multidisciplinary researcher with four years of experience designing, executing, and communicating analyses for both academic and non-technical audiences. I am a fast learner who excels at using programming, modeling, and visualization to elicit insight from diverse data sets.

# EDUCATION

*Bren School of Environmental Science & Mangement, University of California, Santa Barbara* \hfill 2014   
Master of Environmental Science and Management (MESM) 
  
*Bucknell University*  \hfill 2009  
B.A. Economics & Biology, *cum laude* 

# TECHNICAL SKILLS
**Programming** - R (5 years), Python (2 years), HTML/CSS (2 years), Google Earth Engine (2 years)   
**Techniques** - Regression, spatial analysis, structural modeling, optimization, classification, cost-benefit analysis   
**Tools** - GitHub, Shiny, Anaconda, Jupyter, Docker 

# EMPLOYMENT

*Sustainable Fisheries Group (SFG), UC Santa Barbara:* \hfill 2014 - present    
**Project Researcher** \hfill 
  
  - Training a machine learning model (convolutional neural network) to detect multiple types of aquaculture farms in satellite images (Python)
  - Developed a data pipeline to acquire, process, annotate, and manage a XX GB dataset of satellite images (Python)
  - Conducted a suitability analysis and built a spatial bioeconomic model to estimate the potential of Cobia aquaculture in the Caribbean (R)
  - Synthesized data from multiple sources into a comprehensive dataset of global fisheries. Modeled biological and economic outcomes of various management policies for all 4,700 individual fisheries, including optimizing for profits (R)
  - Developed a novel method and global dataset of fish prices estimated from existing public data sources (R)
  - Using git/GitHub for management, collaboration, and publication of all project code 
  - Communicating complex analyses to diverse audiences via peer-reviewed publications, white papers, technical reports, and interactive dashboards 
  - Conducted an economic valuation of marine resources in The Bahamas after mapping and quantifying habitat types (ArcGIS)

*MER Consultants LLC:* \hfill 2017  
**Independent Contractor** 
 
 - Built a simulation model to evaluate management options for the Philippine sardine fishery (R)
 - Developed an interactive decision support tool for the client (R Shiny)

# PUBLICATIONS

Froehlich HE, Jacobsen NS, Essingtington TE, **Clavelle T**, Halpern BS. (2018). Avoiding the ecological limits of forage fish for aquaculture. *Nature Sustainability*, 1(6), 298.

Burgess MG, McDermott GR, Owashi B, Peavey Reeves LE, **Clavelle T**, Ovando D, Wallace BP, Lewison RL, Gaines SD, Costello C. Protecting marine mammals, turtles, and birds by rebuilding global fisheries. (2018). *Science*, 359(6381), 1255-1258. 

Costello C, Ovando D, **Clavelle T**, et al. (2016). Global fishery prospects under contrasting management regimes. *Proceedings of the National Academy of Sciences*, 201520420.

Melnychuk MC, **Clavelle T**, Owashi B, & Strauss CK. (2016). Re-construction of global ex-vessel prices of fished species. *ICES Journal of Marine Science*. doi: 10.1093/icesjms/fsw169.

**Clavelle T**, Lester SE, Gentry R, Froehlich HE. (in review). Interactions and management for the future of marine aquaculture and capture fisheries.

Thomas L, **Clavelle T**, Lester SE, Klinger DH. (in review). Charting an aquaculture future for the Caribbean.

Szuwalski CS, Xianshi J, Xiujuan S, **Clavelle T** (in review). Seafood security via intense exploitation and cultivation: costs, benefits, and risks