---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: rap-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Ryan A. Peek
orcid: "orcid.org/0000-0002-9577-6885"
jobtitle: "PhD Candidate, Ecology, UC Davis"
address: "1000 Tulip Lane · Davis · CA 95618"
fontawesome: yes
email: rapeek@ucdavis.edu
github: ryanpeek
#phone: "+1 555 5555"
web: ryanpeek.github.io
updated: yes

keywords: RMarkdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# EDUCATION

*Bren School of Environmental Science & Mangement, University of California, Santa Barbara*  
Master of Environmental Science and Management (MESM) \hfill 2014  
  
*Bucknell University*, B.A. Economics & Biology, *cum laude* \hfill 2009  

# EMPLOYMENT

*Sustainable Fisheries Group, UC Santa Barbara:*

 > Project Researcher \hfill 2014--present

*MER Consultants LLC:*

 > Independent Contractor \hfill 2017

*Bimini Biological Field Station, Bimini, The Bahamas:*

 > Assistant Lab Manager  \hfill 2010--2011

# PUBLICATIONS

Burgess, M. G., McDermott, G. R., Owashi

Costello, C., Ovando, D., Clavelle, T., Strauss, C. K., Hilborn, R., Melnychuk, M. C., ... & Rader, D. N. (2016). Global fishery prospects under contrasting management regimes. Proceedings of the National Academy of Sciences, 201520420.

Melnychuk, M. C., Clavelle, T., Owashi, B & Strauss, C. K. (2016). Re-construction of global ex-vessel prices of fished species. ICES Journal of Marine Science. doi: 10.1093/icesjms/fsw169.

# PROFESSIONAL AFFILIATIONS & TRAINING	  

  - Software & Data Carpentry Instructor
  - Eco-Data-Science R-Users Group - (https://eco-data-science.github.io)
  
# REFERENCES

Available upon request
